import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Toaster } from '@/components/ui/toaster';

import { cn } from '@/lib/utils';
import Link from 'next/link';
import { buttonVariants } from '@/components/ui/button';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider>
        <head />
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            fontSans.variable,
          )}
        >
          <header className="flex justify-between items-center py-4 px-8 bg-slate-50">
            <h1 className="text-xl">Band Manager</h1>
            <nav className="flex items-center">
              <SignedIn>
                <Link
                  className={buttonVariants({
                    variant: 'default',
                    className: `w-full mr-4`,
                  })}
                  href="/studio/create"
                >
                  Create studio
                </Link>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
              <SignedOut>
                <div className="flex gap-4">
                  <SignUpButton forceRedirectUrl="/studio" />
                  <SignInButton forceRedirectUrl="/studio" />
                </div>
              </SignedOut>
            </nav>
          </header>
          {children}
          <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
